# Site settings
title: login.gov
image: /assets/img/login-gov-288x288.png
canonical_domain: www.login.gov

# i18n
languages:
  - en
  - es
  - fr

exclude_from_localizations: ["javascript", "images", "css"]

# Pages
collections:
  help:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:path/

# Scripts
scripts:
  - /assets/js/build/bundle.js

# Styles
styles:
  - /assets/stylesheets/build/main.css

# Build settings
kramdown:
  hard_wrap: true

# Defaults
defaults:
- scope:
    path: "_help"
  values:
    layout: help
- scope:
    path: ""
  values:
    layout: main

include:
  # dotfiles are excluded by default
  - .well-known

exclude:
  - /assets/stylesheets/main.scss
  - Gemfile*
  - Makefile*
  - node_modules
  - package.json
  - scripts
  - spec
  - webpack.config.js
  - vendor

keep_files:
  - /assets/js/build/*
  - /assets/stylesheets/build/*

plugins:
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin

help_pages:
- creating-an-account
- signing-in
- changing-settings
- privacy-and-security
- security-keys
- trusted-traveler-programs
- usajobs
- sam

# Per-section configs
playbook:
  principles:
   - anchor: users
     img: graphic-users
     text: Focus on user needs
   - anchor: transparent
     img: graphic-venn
     text: Be transparent about how it works
   - anchor: flexible
     img: graphic-half-circle
     text: Build a flexible product
   - anchor: privacy
     img: graphic-locks
     text: Use modern privacy practices
   - anchor: security
     img: graphic-hex
     text: Create responsive security systems
baseurl:
